export const vendingMachineStyles = {
  sectionWrapper: {
    borderColor: "#00897B",
    border: "3px solid #00897B",
    borderRadius: "5px",
    padding: "15px",
    marginBottom: "20px",
  },
  vendingMachine: {
    maxWidth: "950px",
    margin: "0 auto",
    padding: "20px",
    border: "2px solid #ccc",
    borderRadius: "10px",
    backgroundColor: "#F5F5F5",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    textAlign: "center",
  },
  itemList: {
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: "30px",
  },
  itemCard: {
    width: "100%",
    marginBottom: "15px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    backgroundColor: "#FFFFFF",
    border: "1px solid #e0e0e0",
    borderRadius: "5px",
    padding: "15px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    "& button": {
      backgroundColor: "#00897B",
      marginTop: "10px",
    },
    "&:hover": {
      backgroundColor: "#e0f2f1",
    },
  },
  selectedItemCard: {
    borderColor: "#00897B",
    borderWidth: "3px",
    backgroundColor: "#d4d4d4",
  },
  coinButton: {
    width: "80px",
    height: "80px",
    borderRadius: "50%",
    backgroundColor: "#ffd700",
    display: "flex",
    margin: "15px auto",
    justifyContent: "center",
    border: "2px solid #b8860b",
    fontSize: "16px",
    lineHeight: "16px",
    color: "#212121",
    "&:hover": {
      backgroundColor: "#927b00",
    },
  },
  actionButton: {
    margin: "10px 5px",
    minWidth: "80px",
    backgroundColor: "#28a745",
    color: "#212121",
    "&:hover": {
      backgroundColor: "#218838",
    },
  },
  message: {
    marginTop: "10px",
    color: "green",
  },
};
